from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib

from vulnpilot.reachability._common import DependencyClassification


PYTHON_LOCK_FILENAMES = (
    "uv.lock",
    "poetry.lock",
    "pdm.lock",
    "pylock.toml",
)

PIP_INSPECT_PATHS = (
    "pip-inspect.json",
    ".vulnpilot/pip-inspect.json",
)


@dataclass
class PythonManifestDependencies:
    """
    Dependencies found in project declaration files.

    high_confidence:
        pyproject.toml and requirements.in declarations.

    requirements_txt:
        requirements.txt declarations. These have lower
        confidence because the file might be generated by
        pip freeze.
    """

    high_confidence: dict[str, set[str]] = field(
        default_factory=dict
    )
    requirements_txt: dict[str, set[str]] = field(
        default_factory=dict
    )
    manifest_files: set[str] = field(
        default_factory=set
    )

    def add_high_confidence(
        self,
        package_name: str,
        source: str,
    ) -> None:
        self.high_confidence.setdefault(
            package_name,
            set(),
        ).add(source)

        self.manifest_files.add(source)

    def add_requirements_txt(
        self,
        package_name: str,
        source: str,
    ) -> None:
        self.requirements_txt.setdefault(
            package_name,
            set(),
        ).add(source)

        self.manifest_files.add(source)


def normalize_python_package_name(
    package_name: str,
) -> str:
    """
    Normalize Python distribution names.

    Examples:

        Flask-SQLAlchemy -> flask-sqlalchemy
        flask_sqlalchemy -> flask-sqlalchemy
        flask.sqlalchemy -> flask-sqlalchemy
    """
    return re.sub(
        r"[-_.]+",
        "-",
        package_name.strip(),
    ).lower()


def extract_requirement_name(
    requirement: str,
) -> str | None:
    """
    Extract a distribution name from a requirement.

    Supported examples:

        requests>=2.31
        requests[security]>=2.31
        requests @ https://example.com/requests.whl
        -e git+https://example/repo.git#egg=requests
    """
    requirement = requirement.strip()

    if not requirement:
        return None

    if requirement.startswith("#"):
        return None

    egg_match = re.search(
        r"[#&]egg=([A-Za-z0-9][A-Za-z0-9._-]*)",
        requirement,
    )

    if egg_match:
        return normalize_python_package_name(
            egg_match.group(1)
        )

    # Ignore pip options such as:
    #
    # -r other-requirements.txt
    # -c constraints.txt
    # --index-url https://...
    if requirement.startswith("-"):
        return None

    match = re.match(
        r"^([A-Za-z0-9][A-Za-z0-9._-]*)",
        requirement,
    )

    if not match:
        return None

    return normalize_python_package_name(
        match.group(1)
    )


def load_toml_file(
    path: Path,
) -> dict[str, Any] | None:
    try:
        content = path.read_text(
            encoding="utf-8"
        )
        return tomllib.loads(content)
    except (
        OSError,
        UnicodeDecodeError,
        tomllib.TOMLDecodeError,
    ):
        return None


def collect_requirement_names(
    requirements: list[Any],
) -> set[str]:
    dependency_names: set[str] = set()

    for requirement in requirements:
        if not isinstance(requirement, str):
            continue

        dependency_name = extract_requirement_name(
            requirement
        )

        if dependency_name:
            dependency_names.add(
                dependency_name
            )

    return dependency_names


def add_dependencies(
    manifest: PythonManifestDependencies,
    dependency_names: set[str],
    source: str,
    high_confidence: bool,
) -> None:
    for dependency_name in dependency_names:
        if high_confidence:
            manifest.add_high_confidence(
                dependency_name,
                source,
            )
        else:
            manifest.add_requirements_txt(
                dependency_name,
                source,
            )


def read_pyproject_dependencies(
    pyproject_path: Path,
    manifest: PythonManifestDependencies,
) -> None:
    data = load_toml_file(pyproject_path)

    if data is None:
        return

    source = pyproject_path.name
    manifest.manifest_files.add(source)

    project = data.get("project", {})

    if isinstance(project, dict):
        # PEP 621:
        #
        # [project]
        # dependencies = ["requests>=2"]
        project_dependencies = project.get(
            "dependencies",
            [],
        )

        if isinstance(project_dependencies, list):
            add_dependencies(
                manifest=manifest,
                dependency_names=(
                    collect_requirement_names(
                        project_dependencies
                    )
                ),
                source=source,
                high_confidence=True,
            )

        # [project.optional-dependencies]
        # dev = ["pytest"]
        optional_dependencies = project.get(
            "optional-dependencies",
            {},
        )

        if isinstance(
            optional_dependencies,
            dict,
        ):
            for group_dependencies in (
                optional_dependencies.values()
            ):
                if not isinstance(
                    group_dependencies,
                    list,
                ):
                    continue

                add_dependencies(
                    manifest=manifest,
                    dependency_names=(
                        collect_requirement_names(
                            group_dependencies
                        )
                    ),
                    source=source,
                    high_confidence=True,
                )

    # PEP 735:
    #
    # [dependency-groups]
    # dev = ["pytest"]
    dependency_groups = data.get(
        "dependency-groups",
        {},
    )

    if isinstance(dependency_groups, dict):
        for group_dependencies in (
            dependency_groups.values()
        ):
            if not isinstance(
                group_dependencies,
                list,
            ):
                continue

            add_dependencies(
                manifest=manifest,
                dependency_names=(
                    collect_requirement_names(
                        group_dependencies
                    )
                ),
                source=source,
                high_confidence=True,
            )

    tool = data.get("tool", {})

    if not isinstance(tool, dict):
        return

    # Legacy uv development dependencies:
    #
    # [tool.uv]
    # dev-dependencies = ["pytest"]
    uv_configuration = tool.get("uv", {})

    if isinstance(uv_configuration, dict):
        uv_dev_dependencies = (
            uv_configuration.get(
                "dev-dependencies",
                [],
            )
        )

        if isinstance(
            uv_dev_dependencies,
            list,
        ):
            add_dependencies(
                manifest=manifest,
                dependency_names=(
                    collect_requirement_names(
                        uv_dev_dependencies
                    )
                ),
                source=source,
                high_confidence=True,
            )

    # Poetry:
    #
    # [tool.poetry.dependencies]
    # requests = "^2.31"
    poetry = tool.get("poetry", {})

    if not isinstance(poetry, dict):
        return

    poetry_dependencies = poetry.get(
        "dependencies",
        {},
    )

    if isinstance(poetry_dependencies, dict):
        for dependency_name in poetry_dependencies:
            if dependency_name.lower() == "python":
                continue

            manifest.add_high_confidence(
                normalize_python_package_name(
                    dependency_name
                ),
                source,
            )

    # [tool.poetry.group.dev.dependencies]
    # pytest = "^8"
    poetry_groups = poetry.get(
        "group",
        {},
    )

    if not isinstance(poetry_groups, dict):
        return

    for group in poetry_groups.values():
        if not isinstance(group, dict):
            continue

        group_dependencies = group.get(
            "dependencies",
            {},
        )

        if not isinstance(
            group_dependencies,
            dict,
        ):
            continue

        for dependency_name in group_dependencies:
            if dependency_name.lower() == "python":
                continue

            manifest.add_high_confidence(
                normalize_python_package_name(
                    dependency_name
                ),
                source,
            )


def read_requirements_file(
    requirements_path: Path,
) -> set[str]:
    try:
        content = requirements_path.read_text(
            encoding="utf-8"
        )
    except (OSError, UnicodeDecodeError):
        return set()

    dependency_names: set[str] = set()

    for line in content.splitlines():
        dependency_name = (
            extract_requirement_name(line)
        )

        if dependency_name:
            dependency_names.add(
                dependency_name
            )

    return dependency_names


def find_requirement_files(
    project_path: Path,
    suffix: str,
) -> list[Path]:
    patterns = (
        f"requirements{suffix}",
        f"requirements-*{suffix}",
        f"requirements_*{suffix}",
    )

    requirement_files: set[Path] = set()

    for pattern in patterns:
        requirement_files.update(
            project_path.glob(pattern)
        )

    return sorted(requirement_files)


def read_python_manifest_dependencies(
    project_path: Path,
) -> PythonManifestDependencies:
    manifest = PythonManifestDependencies()

    pyproject_path = (
        project_path / "pyproject.toml"
    )

    if pyproject_path.is_file():
        read_pyproject_dependencies(
            pyproject_path=pyproject_path,
            manifest=manifest,
        )

    # requirements.in is normally the human-maintained
    # direct dependency input.
    for requirements_path in (
        find_requirement_files(
            project_path,
            ".in",
        )
    ):
        dependency_names = read_requirements_file(
            requirements_path
        )

        add_dependencies(
            manifest=manifest,
            dependency_names=dependency_names,
            source=requirements_path.name,
            high_confidence=True,
        )

    # requirements.txt might be handwritten or generated
    # by pip freeze/pip-compile, so keep it separate.
    for requirements_path in (
        find_requirement_files(
            project_path,
            ".txt",
        )
    ):
        dependency_names = read_requirements_file(
            requirements_path
        )

        add_dependencies(
            manifest=manifest,
            dependency_names=dependency_names,
            source=requirements_path.name,
            high_confidence=False,
        )

    return manifest


def read_python_lock_packages(
    lock_path: Path,
) -> set[str]:
    data = load_toml_file(lock_path)

    if data is None:
        return set()

    resolved_packages: set[str] = set()

    # uv.lock, poetry.lock and pdm.lock:
    #
    # [[package]]
    # name = "requests"
    package_entries = data.get(
        "package",
        [],
    )

    if isinstance(package_entries, list):
        for package in package_entries:
            if not isinstance(package, dict):
                continue

            name = package.get("name")

            if isinstance(name, str):
                resolved_packages.add(
                    normalize_python_package_name(
                        name
                    )
                )

    # PEP 751 pylock.toml:
    #
    # [[packages]]
    # name = "requests"
    packages_entries = data.get(
        "packages",
        [],
    )

    if isinstance(packages_entries, list):
        for package in packages_entries:
            if not isinstance(package, dict):
                continue

            name = package.get("name")

            if isinstance(name, str):
                resolved_packages.add(
                    normalize_python_package_name(
                        name
                    )
                )

    return resolved_packages


def find_resolved_lockfiles(
    project_path: Path,
    package_name: str,
) -> list[str]:
    target_name = normalize_python_package_name(
        package_name
    )

    resolved_lockfiles: list[str] = []

    for lock_filename in PYTHON_LOCK_FILENAMES:
        lock_path = project_path / lock_filename

        if not lock_path.is_file():
            continue

        resolved_packages = (
            read_python_lock_packages(
                lock_path
            )
        )

        if target_name in resolved_packages:
            resolved_lockfiles.append(
                lock_filename
            )

    return resolved_lockfiles


def find_pip_inspect_report(
    project_path: Path,
) -> Path | None:
    for relative_path in PIP_INSPECT_PATHS:
        report_path = (
            project_path / relative_path
        )

        if report_path.is_file():
            return report_path

    return None


def classify_from_pip_inspect(
    report_path: Path,
    package_name: str,
) -> DependencyClassification | None:
    try:
        report = json.loads(
            report_path.read_text(
                encoding="utf-8"
            )
        )
    except (
        OSError,
        UnicodeDecodeError,
        json.JSONDecodeError,
    ):
        return None

    if report.get("version") != "1":
        return None

    installed_packages = report.get(
        "installed",
        [],
    )

    if not isinstance(installed_packages, list):
        return None

    target_name = normalize_python_package_name(
        package_name
    )

    for installed_package in installed_packages:
        if not isinstance(
            installed_package,
            dict,
        ):
            continue

        metadata = installed_package.get(
            "metadata",
            {},
        )

        if not isinstance(metadata, dict):
            continue

        installed_name = metadata.get("name")

        if not isinstance(installed_name, str):
            continue

        if (
            normalize_python_package_name(
                installed_name
            )
            != target_name
        ):
            continue

        requested = installed_package.get(
            "requested"
        )

        if requested is True:
            return DependencyClassification(
                dependency_type="direct",
                evidence=[
                    (
                        f"{package_name} has "
                        f"requested=true in "
                        f"{report_path.name}"
                    )
                ],
            )

        if requested is False:
            return DependencyClassification(
                dependency_type="transitive",
                evidence=[
                    (
                        f"{package_name} has "
                        f"requested=false in "
                        f"{report_path.name}"
                    )
                ],
            )

        return DependencyClassification(
            dependency_type="unknown",
            evidence=[
                (
                    f"{package_name} is installed according "
                    f"to {report_path.name}, but requested "
                    "metadata is unavailable"
                )
            ],
        )

    return None


def format_sources(
    sources: set[str],
) -> str:
    return ", ".join(sorted(sources))


def classify_python_dependency(
    project_path: Path,
    package_name: str,
) -> DependencyClassification:
    root = project_path.expanduser().resolve()

    target_name = normalize_python_package_name(
        package_name
    )

    manifest = read_python_manifest_dependencies(
        root
    )

    # 1. Strong direct-dependency evidence.
    #
    # pyproject.toml and requirements.in are explicit
    # dependency declarations.
    strong_direct_sources = (
        manifest.high_confidence.get(
            target_name
        )
    )

    if strong_direct_sources:
        return DependencyClassification(
            dependency_type="direct",
            evidence=[
                (
                    f"{package_name} is directly declared "
                    f"in {format_sources(strong_direct_sources)}"
                )
            ],
        )

    # 2. Inspect the actual pip environment.
    #
    # This is checked before requirements.txt because
    # requirements.txt might have been generated by
    # pip freeze.
    pip_inspect_path = find_pip_inspect_report(
        root
    )
    pip_classification = None

    if pip_inspect_path is not None:
        pip_classification = (
            classify_from_pip_inspect(
                report_path=pip_inspect_path,
                package_name=package_name,
            )
        )

        if (
            pip_classification is not None
            and pip_classification.dependency_type
            in {"direct", "transitive"}
        ):
            return pip_classification

    # 3. Lower-confidence direct evidence.
    #
    # Treat requirements.txt entries as direct when no
    # stronger pip-inspect evidence is available.
    requirements_txt_sources = (
        manifest.requirements_txt.get(
            target_name
        )
    )

    if requirements_txt_sources:
        return DependencyClassification(
            dependency_type="direct",
            evidence=[
                (
                    f"{package_name} is declared in "
                    f"{format_sources(requirements_txt_sources)}; "
                    "this file may be handwritten or generated"
                )
            ],
        )

    # 4. Resolved lockfile evidence.
    resolved_lockfiles = (
        find_resolved_lockfiles(
            project_path=root,
            package_name=package_name,
        )
    )

    if (
        resolved_lockfiles
        and manifest.manifest_files
    ):
        return DependencyClassification(
            dependency_type="transitive",
            evidence=[
                (
                    f"{package_name} appears in "
                    f"{', '.join(resolved_lockfiles)}, "
                    "but is not directly declared in the "
                    "project manifests"
                )
            ],
        )

    # 5. Preserve unknown pip-inspect evidence.
    if pip_classification is not None:
        return pip_classification

    # 6. A lockfile without a declaration manifest proves
    # installation/resolution but not directness.
    if resolved_lockfiles:
        return DependencyClassification(
            dependency_type="unknown",
            evidence=[
                (
                    f"{package_name} appears in "
                    f"{', '.join(resolved_lockfiles)}, "
                    "but no direct-dependency manifest "
                    "was found"
                )
            ],
        )

    return DependencyClassification(
        dependency_type="unknown",
        evidence=[
            (
                "No direct declaration or resolved "
                "dependency evidence was found"
            )
        ],
    )
